# ColorLab-Workshop Hugo Configuration
baseURL = "https://vbtien.github.io/ColorLab-Workshop/"
languageCode = "en-us"
title = "ColorLab Workshop - Professional Color Analysis Platform"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Workshop specific settings
  editURL = "https://github.com/VBTIEN/ColorLab-Workshop/edit/master/content"
  description = "Professional Color Analysis Workshop using Advanced Mathematical Algorithms and AWS Serverless Architecture"
  author = "AWS Solutions Architect"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
  # Workshop branding
  workshopTitle = "ColorLab Workshop"
  workshopSubtitle = "Professional Color Analysis Platform"
  workshopDuration = "3.5 hours"
  workshopLevel = "Intermediate"
  
  # Custom CSS and JS
  custom_css = ["css/custom.css"]
  
[Languages]
[Languages.en]
title = "ColorLab Workshop"
weight = 1
languageName = "English"

[Languages.vi]
title = "ColorLab Workshop"
weight = 2
languageName = "Tiếng Việt"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    tabWidth = 2
