# AI Image Analyzer Workshop Configuration

workshop:
  title: "ColorLab - Professional Color Analysis Workshop"
  subtitle: "Advanced color analysis using AWS Lambda and AI algorithms"
  duration: "3-4 hours"
  level: "Intermediate"
  
  # Workshop metadata
  version: "1.0"
  last_updated: "2025-07-10"
  author: "AWS Solutions Architect"
  
  # Target audience
  audience:
    - "Developers interested in AI/ML"
    - "AWS practitioners"
    - "Students learning cloud computing"
    - "Anyone interested in image processing"

  # Prerequisites
  prerequisites:
    required:
      - "AWS Account with admin access"
      - "Basic programming knowledge"
      - "Web browser"
      - "Text editor"
    recommended:
      - "Python experience"
      - "HTML/CSS knowledge"
      - "AWS services familiarity"

  # Learning objectives
  objectives:
    - "Build serverless image analysis applications"
    - "Implement advanced color analysis algorithms"
    - "Create professional web interfaces"
    - "Deploy full-stack applications on AWS"
    - "Optimize performance and costs"

  # AWS services used
  aws_services:
    primary:
      - "AWS Lambda"
      - "Amazon S3"
      - "Amazon API Gateway"
      - "AWS IAM"
    future:
      - "Amazon Rekognition"
      - "Amazon Bedrock"
      - "Amazon CloudWatch"

  # Workshop modules
  modules:
    - id: "00"
      title: "Prerequisites & Setup"
      duration: "30 min"
      type: "setup"
      description: "Environment setup and AWS configuration"
      
    - id: "01"
      title: "Architecture Overview"
      duration: "20 min"
      type: "theory"
      description: "Understanding the solution architecture"
      
    - id: "02"
      title: "Backend Development"
      duration: "60 min"
      type: "hands-on"
      description: "Building Lambda function for image analysis"
      labs:
        - "Lambda Function Creation"
        - "Lambda Layers Setup"
        - "Algorithm Implementation"
        
    - id: "03"
      title: "API Gateway Setup"
      duration: "30 min"
      type: "hands-on"
      description: "Creating RESTful API"
      labs:
        - "REST API Creation"
        - "CORS Configuration"
        - "API Testing"
        
    - id: "04"
      title: "Frontend Development"
      duration: "45 min"
      type: "hands-on"
      description: "Building web interface"
      labs:
        - "HTML/CSS/JavaScript Setup"
        - "Image Upload Functionality"
        - "Results Visualization"
        
    - id: "05"
      title: "S3 Integration"
      duration: "20 min"
      type: "hands-on"
      description: "Static website hosting"
      labs:
        - "S3 Bucket Creation"
        - "Static Website Configuration"
        - "File Upload and Testing"
        
    - id: "06"
      title: "Advanced Features"
      duration: "30 min"
      type: "hands-on"
      description: "Color analysis enhancements"
      labs:
        - "K-Means++ Implementation"
        - "LAB Color Space"
        - "Performance Optimization"
        
    - id: "07"
      title: "Testing & Wrap-up"
      duration: "15 min"
      type: "testing"
      description: "End-to-end testing and next steps"

  # Cost estimation
  costs:
    workshop_cost: "< $5"
    monthly_free_tier:
      lambda: "1M requests"
      api_gateway: "1M requests"
      s3: "5GB storage"
    estimated_free_analyses: "100,000/month"

  # Technical specifications
  technical:
    lambda:
      runtime: "python3.11"
      memory: "2048 MB"
      timeout: "120 seconds"
      layers: ["PIL/Pillow", "NumPy"]
    
    algorithms:
      primary: "K-Means++ Clustering"
      color_space: "LAB (perceptually uniform)"
      accuracy_improvement: "70%"
      
    performance:
      processing_time: "1-3 seconds"
      api_response: "< 5 seconds"
      concurrent_users: "1000+"

  # Resources and links
  resources:
    documentation:
      - title: "AWS Lambda Developer Guide"
        url: "https://docs.aws.amazon.com/lambda/"
      - title: "API Gateway Developer Guide"
        url: "https://docs.aws.amazon.com/apigateway/"
      - title: "PIL/Pillow Documentation"
        url: "https://pillow.readthedocs.io/"
    
    sample_code:
      github_repo: "https://github.com/[YOUR-USERNAME]/ai-image-analyzer-workshop"
      lambda_function: "lambda_function_colorlab_complete.py"
      web_interface: "web_interface_ultimate_final.html"
    
    support:
      - "Workshop instructor"
      - "AWS documentation"
      - "Community forums"
      - "GitHub issues"

  # Success metrics
  success_metrics:
    completion_rates:
      basic_deployment: "100%"
      color_analysis: "90%"
      web_interface: "80%"
      advanced_features: "70%"
    
    learning_outcomes:
      - "Understand serverless architecture"
      - "Implement image processing algorithms"
      - "Deploy full-stack AWS applications"
      - "Optimize performance and costs"

# Workshop branding
branding:
  primary_color: "#FF6B35"  # Orange
  secondary_color: "#004E89"  # Blue
  accent_color: "#1A936F"   # Green
  
  logo: "🎨"
  tagline: "Transform images into insights with AWS AI"
  
  social:
    hashtag: "#AWSImageAnalyzer"
    twitter: "@AWSWorkshops"
    
# Deployment information
deployment:
  live_demo: "http://ai-image-analyzer-web-1751723364.s3-website-ap-southeast-1.amazonaws.com"
  api_endpoint: "https://cuwg234q8g.execute-api.ap-southeast-1.amazonaws.com/prod/analyze"
  region: "ap-southeast-1"
  
  status: "Production Ready"
  last_tested: "2025-07-10"
  all_issues_resolved: true
